#!/data/data/com.termux/files/usr/bin/bash

echo "To download as mp3 type 1"
echo "To download as mp4 type 2"
echo "To torrent to server type 3"

read option

if [ "$option" -eq "1" ]
then
	echo "To download to ~/shared/Music/ type 1"
	echo "To download to ~/shared/Podcasts/ type 2"
	
	read option

	if [ "$option" -eq "1" ]
	then
		download_dir="~/storage/shared/Music/"
	elif [ "$option" -eq "2" ]
	then
		download_dir="~/storage/shared/Podcasts/"
	fi

	yt-dlp --extract-audio --audio-format mp3 --prefer-ffmpeg $1 -o "${download_dir}%(title)s.%(ext)s"
elif [ "$option" -eq "2" ]
then
	yt-dlp --format "bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best" --merge-output-format mp4 $1 -o "~/storage/shared/Movies/youtube/%(title)s.%(ext)s"
elif [ "$option" -eq "3" ]
then                                                            echo "To torrent as show type 1"
        echo "To torrent as movie type 2"               
        read option                                     
        if [ "$option" -eq "1" ]                                then
                torrent_dir="/var/lib/plexmediaserver/shows"
        elif [ "$option" -eq "2" ]                              then
                torrent_dir="/var/lib/plexmediaserver/movies"
        fi                                              
        ssh -t {user}@{url} -p {ip} "sudo transmission-cli -f kill-all-transmission.ssh \"$1\" -w $torrent_dir"
fi
